language: rust

branches:
  only:
    - master

rust:
  - 1.25.0
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

notifications:
  irc: 'irc.mozilla.org#rustsec'
