language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - 1.35.0
  - stable
  - beta

os:
  - linux
  - osx
  - windows

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy --all
  - cargo test --release
  - cargo doc --no-deps
  - cargo run audit

matrix:
  fast_finish: true
  allow_failures:
    - os: windows
