[package]
name          = "cargo-audit"
description   = "Audit Cargo.lock for crates with security vulnerabilities"
version       = "0.5.2"
authors       = ["Tony Arcieri <bascule@gmail.com>"]
license       = "MIT OR Apache-2.0"
homepage      = "https://github.com/rustsec/cargo-audit"
readme        = "README.md"
categories    = ["development-tools"]
keywords      = ["cargo-subcommand", "security", "audit", "vulnerability"]

[[bin]]
name = "cargo-audit"

[dependencies]
atty = "0.2"
gumdrop = "0.5"
gumdrop_derive = "0.5"
lazy_static = "1"
platforms = "0.1"
rustsec = "0.9.3"
term = "0.5"
serde_json = "1"

