[package]
name        = "cargo-audit"
description = "Audit Cargo.lock for crates with security vulnerabilities"
version     = "0.7.0"
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/cargo-audit"
readme      = "README.md"
categories  = ["development-tools"]
keywords    = ["cargo-subcommand", "security", "audit", "vulnerability"]
edition     = "2018"

[dependencies]
failure = "0.1"
gumdrop = "0.6"
home = "0.3"
lazy_static = "1"
platforms = "0.2"
rustsec = "0.12"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"

[dependencies.abscissa_core]
version = "0.2.0-rc.1"

[dev-dependencies.abscissa_core]
version = "0.2.0-rc.1"
features = ["testing"]

[dev-dependencies]
assert_cmd = "0.11"
serial_test = "0.2"
serial_test_derive = "0.2"
tempfile = "3.0.8"
